(() => {
const cfg=window.WMP_CONFIG; const movieGenres={12:'Aventura',14:'Fantasía',16:'Animación',18:'Drama',27:'Terror',28:'Acción',35:'Comedia',36:'Historia',37:'Western',53:'Suspenso',80:'Crimen',99:'Documental',878:'Ciencia ficción',9648:'Misterio',10402:'Música',10749:'Romance',10751:'Familia',10752:'Bélica',10770:'TV'}; const tvGenres={16:'Animación',18:'Drama',35:'Comedia',37:'Western',80:'Crimen',99:'Documental',9648:'Misterio',10751:'Familia',10759:'Acción y aventura',10762:'Infantil',10763:'Noticias',10764:'Reality',10765:'Ciencia ficción y fantasía',10766:'Telenovela',10767:'Talk show',10768:'Guerra y política'};
const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const pageKey='wmp:'+location.pathname;
function saveScroll(){sessionStorage.setItem(pageKey+':scroll',String(scrollY));}
addEventListener('beforeunload',saveScroll); addEventListener('pagehide',saveScroll); addEventListener('pageshow',()=>requestAnimationFrame(()=>scrollTo(0,Number(sessionStorage.getItem(pageKey+':scroll')||0))));
function goBack(){history.length>1?history.back():location.href='index.html'}
$$('[data-back]').forEach(b=>b.addEventListener('click',goBack));
$$('[data-search-toggle]').forEach(b=>b.addEventListener('click',()=>$('.search-panel')?.classList.toggle('open')));
function normalize(s){return (s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();}
function formatDate(s,year){if(!s)return `01/01/${year}`;const [y,m,d]=s.split('-');return `${d}/${m}/${y}`}
async function enrich(item){const ck='wmp:tmdb:'+item.type+':'+item.query+':'+item.year;const cached=localStorage.getItem(ck);if(cached){try{return {...item,...JSON.parse(cached)}}catch{}}
 const type=item.type; const yearParam=type==='movie'?'year':'first_air_date_year'; const url=`https://api.themoviedb.org/3/search/${type}?api_key=${cfg.tmdbApiKey}&language=es-MX&query=${encodeURIComponent(item.query)}&${yearParam}=${item.year}`;
 try{const r=await fetch(url);if(!r.ok)throw 0;const data=await r.json();const x=data.results?.[0];if(!x)throw 0;const release=x.release_date||x.first_air_date||`${item.year}-01-01`;const genres=(x.genre_ids||[]).map(id=>(type==='movie'?movieGenres:tvGenres)[id]).filter(Boolean);const out={tmdbId:x.id,title:x.title||x.name||item.title,overview:x.overview||'',poster:x.poster_path?cfg.imageBase+x.poster_path:'',backdrop:x.backdrop_path?cfg.backdropBase+x.backdrop_path:'',score:Number(x.vote_average||0).toFixed(1),releaseDate:release,genres};localStorage.setItem(ck,JSON.stringify(out));return {...item,...out};}catch{return {...item,score:'—',releaseDate:`${item.year}-01-01`,genres:[],overview:'Información no disponible.',poster:'',backdrop:''}}
}
function card(item){const a=document.createElement('article');a.className='card';a.dataset.search=[item.title,item.year,item.releaseDate,formatDate(item.releaseDate,item.year),...(item.genres||[])].join(' ');a.dataset.date=item.releaseDate||`${item.year}-01-01`;a.innerHTML=`<a class="poster" href="${item.href}" aria-label="Abrir ${item.title}">${item.poster?`<img src="${item.poster}" alt="${item.title}" loading="lazy">`:`<div class="loading">${item.title}</div>`}<span class="score">★ ${item.score||'—'}</span><button class="fav" type="button" aria-label="Favorito">♡</button></a><h3 title="${item.title}">${item.title}</h3><p class="meta">${item.year}${item.genres?.[0]?' · '+item.genres[0]:''}</p>`;a.querySelector('.poster').addEventListener('click',saveScroll);a.querySelector('.fav').addEventListener('click',e=>{e.preventDefault();e.stopPropagation();e.currentTarget.textContent=e.currentTarget.textContent==='♡'?'♥':'♡'});return a}
async function renderHome(){const movieRail=$('#movieRail'),seriesRail=$('#seriesRail');if(!movieRail)return;let movies=await Promise.all(window.WMP_MOVIES.map(enrich));let series=await Promise.all(window.WMP_SERIES.map(enrich));movies.sort((a,b)=>b.releaseDate.localeCompare(a.releaseDate));series.sort((a,b)=>b.releaseDate.localeCompare(a.releaseDate));movies.slice(0,10).forEach(x=>movieRail.append(card(x)));series.slice(0,10).forEach(x=>seriesRail.append(card(x)));setupHero([...movies.slice(0,3),...series.slice(0,2)]);}
function setupHero(items){const hero=$('.hero'),bg=$('.hero-bg'),title=$('#heroTitle'),desc=$('#heroDesc'),play=$('#heroPlay'),info=$('#heroInfo'),dots=$('.dots');if(!hero||!items.length)return;let i=0,t;const show=n=>{i=(n+items.length)%items.length;const x=items[i];bg.style.backgroundImage=`url('${x.backdrop||x.poster||''}')`;title.textContent=x.title;desc.textContent=x.overview||`${x.year}${x.genres?.length?' · '+x.genres.join(', '):''}`;play.href=x.href;info.href=x.href;$$('.dot',dots).forEach((d,k)=>d.classList.toggle('active',k===i));};items.forEach((_,k)=>{const d=document.createElement('button');d.className='dot';d.addEventListener('click',()=>{show(k);restart()});dots.append(d)});const restart=()=>{clearInterval(t);t=setInterval(()=>show(i+1),6000)};show(0);restart();}
async function renderCatalog(type){const grid=$('#catalogGrid');if(!grid)return;const source=type==='movie'?window.WMP_MOVIES:window.WMP_SERIES;let items=await Promise.all(source.map(enrich));items.sort((a,b)=>b.releaseDate.localeCompare(a.releaseDate));items.forEach(x=>grid.append(card(x)));const input=$('#catalogSearch');const stateKey=pageKey+':query';input.value=sessionStorage.getItem(stateKey)||'';const filter=()=>{const q=normalize(input.value.trim());sessionStorage.setItem(stateKey,input.value);let visible=0;$$('.card',grid).forEach(el=>{const ok=!q||normalize(el.dataset.search).includes(q);el.classList.toggle('hidden',!ok);if(ok)visible++});$('#empty')?.classList.toggle('hidden',visible!==0)};input.addEventListener('input',filter);filter();}
document.addEventListener('DOMContentLoaded',()=>{const type=document.body.dataset.catalog;if(type)renderCatalog(type);else renderHome();});
})();
